/* Synthetic preview data only. No corporate email is included. */
window.OutlookDigestSample = (() => {
  const folders = ['Humain', 'Virtus/Universe', 'Blackfuel', 'Akur', 'Vaultica', 'Whitbread', 'Risk Mgmt', 'Admins', 'Centrica', 'Resources', 'Sent Items', 'Resets', 'Auto Emails', 'Misano - EIP', 'D-MARIN', 'Auto reply/undeliverables', 'Daily Carry', 'Prelim PnL', 'Conversation History'];
  const subjects = ['RE: HUMAIN/Infra - GPU Facility Documents', 'RE: HUMAIN Financing Programme - GPU/DC Insurance DD (Marsh)', 'Re: HumAIn convo with Samih', 'Re: INFRA - Humain - GPU financing report - summary', 'RE: [External] RE: HUMAIN AI Infrastructure Program', 'Re: HUMAIN GPU DD - CDD & TDD', 'RE: GPU Financing: Documentation', 'Project HUMAIN - Power Assets Financing - Bankability', 'RE: HUMAIN - xAI Financing Follow-up (Weekly Call)', 'RE: Goldman Sachs Financing Strategy', 'Re: Humain | GPU | timeline call', 'Re: Financing Strategy', 'Re: Compute BU Peers & Leverage', 'RE: HUMAIN - Pending items to approach Infra ExCom', 'RE: HUMAIN: Weekly Call (Internal)', 'RE: HUMAIN - xAI Financing - Draft PIM', 'HUMAIN RCF - Finance Documents', 'HUMAIN Declined', 'RE: POSTPONED: Humain AMD Cluster Project Finance', 'Re: HUMAIN Phase 1 initial walkthrough', 'RE: AMD GPU Model Audit', 'Response Required - CMCC Minutes: HUMAIN', 'Re: AMD Insurance', 'RE: AMD Updated Financial Model', 'Re: US EXIM', 'RE: HUMAIN - GPU', 'HUMAIN 2025 Financials'];
  const people = ['Daniel Morgan', 'Alex Taylor', 'Sam Burton', 'Omar Aziz', 'Razan Malik', 'Amir Asad', 'Kyle Jackson'];
  const address = name => `${name} <${name.toLowerCase().replaceAll(' ', '.')}@example.com>`;
  const messages = Array.from({ length: 168 }, (_, i) => {
    const day = 11 - Math.floor(i / 30);
    const hour = Math.max(0, 12 - Math.floor((i % 30) / 3));
    const subject = subjects[i % subjects.length];
    const body = `Hi team,\n\nPlease find the latest update on ${subject.replace(/^RE: /i, '')}.\n\nWe look forward to receiving your feedback on the preliminary report. Please let us know if any further information is needed.\n\nRegards,\n${people[i % people.length]}\n\nAdvisory team\nExample Company\n\nThis is synthetic preview content, not a real email.`;
    return { id: `message-${i}`, chainId: `chain-${i % 27}`, folder: i % 4 === 0 ? 'Virtus/Universe' : 'Humain', received: `2026-09-${String(day).padStart(2, '0')}T${String(hour).padStart(2, '0')}:${i % 2 ? '58' : '01'}:00Z`, from: address(people[i % people.length]), to: address(people[(i + 2) % people.length]), cc: '', subject, attachments: i % 8, body, rawBody: `<html xmlns:v="urn:schemas-microsoft-com:vml">\n<head>\n<meta name="Generator" content="Microsoft Word (filtered medium)">\n<style>\n${Array.from({ length: 12 }, () => '@font-face\n {font-family:Calibri;\n panose-1:2 15 5 2 2 2 4 3 2 4;}').join('\n')}\n</style>\n</head>\n<body>\n${body}\n</body>\n</html>` };
  });
  const chains = subjects.map((subject, i) => ({ id: `chain-${i}`, folder: 'Humain', count: [3, 10, 15, 31, 40, 3, 6, 1, 4, 1, 32, 13][i % 12], received: messages[i].received, subject, from: messages[i].from, to: messages[i].to, body: `Subject: ${subject}\n${'='.repeat(90)}\n\n[${messages[i].received}] ${messages[i].from} > ${messages[i].to}\n\n${messages[i].body}\n\n${'-'.repeat(80)}\nEarlier message (synthetic preview)\n\nThank you for sharing the documents. We will review and revert with comments.` }));
  const boilerplates = [
    'This e-mail may contain information that is confidential, privileged or otherwise protected from disclosure. If you are not an intended recipient of this e-mail, do not duplicate or redistribute it by any means. Please delete it and any attachments and notify the sender that you have received it in error. Unintended recipients are prohibited from taking action on the basis of information in this e-mail.\nE-mail messages may contain computer viruses or other defects, may not be accurately replicated on other systems, or may be intercepted.',
    'This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and delete this e-mail.\nAny unauthorised copying, disclosure or distribution of the material in this e-mail is prohibited.',
    'Please consider the environment before printing this email.\nThis communication contains information which is privileged. It is for the exclusive use of the addressee. If you are not the addressee please note that any distribution, reproduction, copying or publication or use of this communication or the information in it is prohibited.',
    'See https://example.com/disclaimer for important information regarding this message and your reliance on information contained in it. This message may contain information that is confidential or privileged. If you are not the intended recipient, please advise the sender immediately and delete this message.',
    'See https://example.com/disclosures for important disclosures relating to regulated transactions.',
    '© Copyright 2026 Example Company. All rights reserved. See https://example.com/disclaimer for risk disclosure, order handling practices, conflicts of interest and other terms and conditions relating to this e-mail and your reliance on it.',
    'Your Personal Data: We may collect and process information about you that may be subject to data protection laws. For more information about how we use and disclose your personal data, how we protect your information, our legal basis to use your information, your rights and who you can contact, please refer to https://example.com/privacy.',
    'This message and any attachment are confidential and may be privileged or otherwise protected from disclosure. If you are not the intended recipient, please notify the sender immediately and delete this message and any attachment from your system. Do not copy them or disclose the contents to any other person.',
    'Example Advisory LLP is a limited liability partnership registered in England & Wales. The registered office and principal place of business are available on our website. A list of members is available at the registered office. Each of these entities is authorised and regulated by the relevant authority.',
    'For details of our complaints procedure, see https://example.com/complaints.\nFor further details, please visit our website.\nEmail communications may be monitored as permitted by applicable law and regulations.\nFor details of how we process personal data, please see our updated Privacy statement.'
  ];
  return { account: 'Local mailbox', lastSynced: '2026-09-11T12:40:06', totalRows: 6644, folders, messages, chains,
    prompts: [
      { title: 'Task tracking (ball in court)', text: 'Explain key timeline and developments\nTell me what is pending with who for any outstanding items\n\nBe succinct and return a table.' },
      { title: 'TS Summary', text: 'What have been the key developments in this discussion?\n\nList all important points of contention, and explain these non-technical language very succinctly.' },
      { title: 'Disclaimers', text: 'How many different disclaimers are there? Is it possible to remove all the disclaimers deterministically? I have a database of individual message contents, not full chains.' },
      { title: 'Process summary', text: 'Build an overall picture of the project.\n\nExplain to a project management agent, using a chart, the process of the entire deal. Explain the sequences clearly.' },
      { title: 'General chain summary', text: 'Summarize the chain succinctly in bullet points, focusing on who raised what point, in chronological order.' }
    ], disclaimers: Array.from({ length: 15 }, (_, i) => ({ text: boilerplates[i % boilerplates.length], enabled: true })), autoClean: false };
})();
